package main

import (
	"fmt"
	"path/filepath"
	"sort"
	"strings"
	"text/template"

	"github.com/kilnx-org/kilnx/internal/lexer"
	"github.com/kilnx-org/kilnx/internal/spec"

	_ "github.com/kilnx-org/kilnx/internal/parser"
)

type scopeGroup struct {
	Scope string
	Attrs []spec.Entity
}

type sinceGroup struct {
	Since    string
	Keywords []spec.Entity
	Attrs    []spec.Entity
}

type agentsCtx struct {
	Keywords          []spec.Entity
	AttributesByScope []scopeGroup
	FieldTypes        []string
	FieldConstraints  []string
	LatestSince       string
	NewKeywords       []spec.Entity
	NewAttrs          []spec.Entity
	History           []sinceGroup
}

// generateAgents writes AGENTS.md as a sibling of the docs output
// root. With the default invocation (-o pointing at docs/), this puts
// AGENTS.md at the repo root. Test invocations using a temp -o get
// their AGENTS.md in the parent dir, which keeps the CI diff symmetric.
// The file is a pointer document for AI coding agents: fixed workflow
// and reading order on top, catalog autogenerated from the spec
// registry below.
func generateAgents(docsOut string, tmpl *template.Template) error {
	keywords := spec.ByKind(spec.KindKeyword)
	attributes := spec.ByKind(spec.KindAttribute)

	ctx := agentsCtx{
		Keywords:          keywords,
		AttributesByScope: groupAttrsByScope(attributes),
		FieldTypes:        lexer.FieldTypes(),
		FieldConstraints:  lexer.FieldConstraints(),
	}

	ctx.LatestSince = latestSince(keywords, attributes)
	ctx.NewKeywords = filterSince(keywords, ctx.LatestSince)
	ctx.NewAttrs = filterSince(attributes, ctx.LatestSince)
	ctx.History = groupBySince(keywords, attributes)

	parent := filepath.Dir(docsOut)
	if parent == "" {
		parent = "."
	}
	path := filepath.Join(parent, "AGENTS.md")
	if err := writeTemplate(tmpl, "agents.md.tmpl", path, ctx); err != nil {
		return fmt.Errorf("render agents: %w", err)
	}
	fmt.Println("wrote", path)
	return nil
}

// groupAttrsByScope buckets attributes by their ParentScope entries.
// An attribute with multiple parents appears under each. Top-level
// attributes (no parent) land under "(top-level)". Buckets sorted by
// scope name; entries within each bucket sorted by attribute name.
func groupAttrsByScope(attrs []spec.Entity) []scopeGroup {
	buckets := map[string][]spec.Entity{}
	for _, a := range attrs {
		if len(a.ParentScope) == 0 {
			buckets["(top-level)"] = append(buckets["(top-level)"], a)
			continue
		}
		for _, p := range a.ParentScope {
			buckets[p] = append(buckets[p], a)
		}
	}
	scopes := make([]string, 0, len(buckets))
	for s := range buckets {
		scopes = append(scopes, s)
	}
	sort.Strings(scopes)
	out := make([]scopeGroup, 0, len(scopes))
	for _, s := range scopes {
		entries := buckets[s]
		sort.Slice(entries, func(i, j int) bool { return entries[i].Name < entries[j].Name })
		out = append(out, scopeGroup{Scope: s, Attrs: entries})
	}
	return out
}

// latestSince returns the highest Since version string across all
// entries, ignoring entries with empty Since. Comparison is the
// natural semver-ish ordering produced by sort.Strings on "0.1.X"
// style values, which works for the kilnx version space.
func latestSince(groups ...[]spec.Entity) string {
	seen := map[string]bool{}
	for _, g := range groups {
		for _, e := range g {
			if e.Since != "" {
				seen[e.Since] = true
			}
		}
	}
	vs := make([]string, 0, len(seen))
	for v := range seen {
		vs = append(vs, v)
	}
	sort.Strings(vs)
	if len(vs) == 0 {
		return ""
	}
	return vs[len(vs)-1]
}

func filterSince(entries []spec.Entity, since string) []spec.Entity {
	if since == "" {
		return nil
	}
	out := make([]spec.Entity, 0, len(entries))
	for _, e := range entries {
		if e.Since == since {
			out = append(out, e)
		}
	}
	return out
}

// groupBySince returns one bucket per Since version, descending
// (newest first), each containing Keywords and Attributes added in
// that release.
func groupBySince(keywords, attrs []spec.Entity) []sinceGroup {
	versions := map[string]*sinceGroup{}
	add := func(e spec.Entity, isKw bool) {
		if e.Since == "" {
			return
		}
		g, ok := versions[e.Since]
		if !ok {
			g = &sinceGroup{Since: e.Since}
			versions[e.Since] = g
		}
		if isKw {
			g.Keywords = append(g.Keywords, e)
		} else {
			g.Attrs = append(g.Attrs, e)
		}
	}
	for _, e := range keywords {
		add(e, true)
	}
	for _, e := range attrs {
		add(e, false)
	}
	vs := make([]string, 0, len(versions))
	for v := range versions {
		vs = append(vs, v)
	}
	sort.Sort(sort.Reverse(sort.StringSlice(vs)))
	out := make([]sinceGroup, 0, len(vs))
	for _, v := range vs {
		g := versions[v]
		sort.Slice(g.Keywords, func(i, j int) bool { return g.Keywords[i].Name < g.Keywords[j].Name })
		sort.Slice(g.Attrs, func(i, j int) bool { return g.Attrs[i].Name < g.Attrs[j].Name })
		out = append(out, *g)
	}
	return out
}

// firstLine returns the first non-empty line of s, useful for
// trimming multi-paragraph summaries down to a single tabular cell.
func firstLine(s string) string {
	for _, line := range strings.Split(s, "\n") {
		line = strings.TrimSpace(line)
		if line != "" {
			return line
		}
	}
	return ""
}
