blank_issues_enabled: true
contact_links:
  - name: Documentation
    url: https://docs.kilnx.org/docs/getting-started
    about: Check the docs before opening an issue
  - name: Discord
    url: https://discord.gg/AJcw5eee54
    about: Ask the community on Discord
